# docker compose up --build
# docker compose up -d --build
# docker inspect bugucms-stanalone | grep IPAddres

version: '3'
services:
  bugucms-stanalone:
    image: terwer/bugucms-standalone:1.0.1
    container_name: bugucms-standalone-1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    stdin_open: true
    tty: true
    restart: "no"